version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

  users-api:
    build:
      context: ../UsersAPI/UsersAPI
      dockerfile: Dockerfile
    container_name: users-api
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
      - JWT_SECRET_KEY=c6b5cbdc128daa0d2cd2726eacaae1266f8c8ee24fffd3e3f2bac1302b55069f
    depends_on:
      rabbitmq:
        condition: service_healthy

  catalog-api:
    build:
      context: ../CatalogAPI/CatalogAPI
      dockerfile: Dockerfile
    container_name: catalog-api
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
      - JWT_SECRET_KEY=c6b5cbdc128daa0d2cd2726eacaae1266f8c8ee24fffd3e3f2bac1302b55069f
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017
      - ConnectionStrings__Redis=redis:6379
      - DatabaseName=CatalogDb
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

  payments-api:
    build:
      context: ../PaymentsAPI/PaymentsAPI
      dockerfile: Dockerfile
    container_name: payments-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  notifications-api:
    build:
      context: ../NotificationsAPI/NotificationsAPI
      dockerfile: Dockerfile
    container_name: notifications-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  fiap-web:
    image: nginx:alpine
    container_name: fiap-web
    ports:
      - "80:80"
    volumes:
      - ../FiapCloudGames-Web:/usr/share/nginx/html
    depends_on:
      - users-api
      - catalog-api
